import React from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
type RealBenchmark={generatedAt:string;network:string;chainId:number;total:number;expectedAllow:number;expectedBlock:number;successfulReceipts:number;revertedReceipts:number;falseAllow:number;falseBlock:number;deployments:Record<string,string>;metrics:{latencyMs:{p50:number;p95:number;p99:number;max:number};gasUsedTotal:string;gasUsedAverage:number;elapsedMs:number};records:Array<{index:number;expected:string;result:string;txHash:string;explorer:string;blockNumber:number;gasUsed:string;nonce:string;guardianDecision:string;latencyMs:number;error:string}>};
type FastBenchmark={generatedAt:string;total:number;expectedAllows:number;expectedBlocks:number;actualAllows:number;actualBlocks:number;falseAuthorizationRate:number;falseBlockRate:number;latencyMs:{p50:number;p95:number;p99:number;max:number};classes:Record<string,number>};
type RiskSignal={source:string;category:string;severity:string;confidence:number;code:string;message:string;evidence:Record<string,unknown>;observedAt:string};type RiskDemo={ok:boolean;source:string;chainId:number;target:string;assessment:{status:string;score:number;confidence:number;degraded:boolean;signals:RiskSignal[]}};type Data={real100:RealBenchmark;benchmark10k:FastBenchmark;risk:RiskDemo};
const short=(v:string)=>v.slice(0,10)+"…"+v.slice(-8); const fmt=(n:number)=>new Intl.NumberFormat("en-US").format(n);
function Metric(p:{label:string;value:string;sub?:string}){return <div className="metric"><span>{p.label}</span><strong>{p.value}</strong>{p.sub&&<small>{p.sub}</small>}</div>}
function App(){const[data,setData]=React.useState<Data|null>(null);const[error,setError]=React.useState("");React.useEffect(()=>{Promise.all([fetch("/v1/benchmark").then(r=>r.json()),fetch("/v1/risk/demo").then(r=>r.json())]).then(([benchmark,risk])=>setData({...benchmark,risk})).catch(e=>setError(String(e)))},[]);if(error)return <main><div className="error">Dashboard data unavailable: {error}</div></main>;if(!data)return <main><div className="loading">Loading live benchmark evidence…</div></main>;const r=data.real100,b=data.benchmark10k;return <main>
<header><div><p className="eyebrow">CWF SECURITY EVIDENCE</p><h1>Agent Guardian</h1><p className="lede">Deterministic policy enforcement for autonomous agent transactions.</p></div><div className="network"><span>●</span> Arbitrum Sepolia · {r.chainId}</div></header>
<section className="hero"><div><p className="eyebrow">REAL CHAIN VALIDATION</p><h2>100 mined executions. <em>0 authorization errors.</em></h2><p>50 authorized calls succeeded and 50 unauthorized calls reverted on Arbitrum Sepolia.</p></div><div className="hero-score"><strong>0</strong><span>false ALLOW / false BLOCK</span></div></section>
<section className="grid metrics"><Metric label="Real executions" value={fmt(r.total)} sub="50 ALLOW · 50 BLOCK"/><Metric label="10k authorization" value={fmt(b.total)} sub="local EVM · real Guard"/><Metric label="Real p50 latency" value={r.metrics.latencyMs.p50.toFixed(0)+" ms"} sub={"p95 "+r.metrics.latencyMs.p95.toFixed(0)+" ms"}/><Metric label="Average gas" value={fmt(Math.round(r.metrics.gasUsedAverage))} sub="per mined execution"/></section>
<section className="grid split"><div className="card"><div className="cardhead"><h3>Authorization benchmark</h3><span>10,000 checks</span></div><div className="bars"><div><b>ALLOW</b><i style={{width:(b.actualAllows/b.total*100)+"%"}}></i><strong>{fmt(b.actualAllows)}</strong></div><div><b>BLOCK</b><i style={{width:(b.actualBlocks/b.total*100)+"%"}}></i><strong>{fmt(b.actualBlocks)}</strong></div></div><p className="note">False authorization rate: <strong>0</strong> · False block rate: <strong>0</strong></p></div>
<div className="card"><div className="cardhead"><h3>Real-chain receipts</h3><span>{r.generatedAt.slice(0,10)}</span></div><div className="receipt"><span className="allow">ALLOW</span><strong>{r.successfulReceipts}</strong><small>successful receipts</small></div><div className="receipt"><span className="block">BLOCK</span><strong>{r.revertedReceipts}</strong><small>reverted receipts</small></div></div></section>
<section className="card"><div className="cardhead"><h3>Live Risk Intelligence</h3><span>{data.risk.assessment.degraded?"DEGRADED":"REAL RPC EVIDENCE"}</span></div><div className="riskgrid"><div><span className="eyebrow">STATUS</span><strong className={data.risk.assessment.status==="BLOCK"?"block":"allow"}>{data.risk.assessment.status}</strong></div><div><span className="eyebrow">RISK SCORE</span><strong>{data.risk.assessment.score.toFixed(1)} / 100</strong></div><div><span className="eyebrow">CONFIDENCE</span><strong>{(data.risk.assessment.confidence*100).toFixed(0)}%</strong></div><div><span className="eyebrow">TARGET</span><code>{short(data.risk.target)}</code></div></div><p className="note">Read-only evidence from the real benchmark target on Arbitrum Sepolia. Risk intelligence is advisory; deterministic Guardian authorization remains the final boundary.</p><div className="signals">{data.risk.assessment.signals.map(s=><div className="signal" key={s.code}><span className={s.severity==="CRITICAL"||s.severity==="HIGH"?"block":"allow"}>{s.severity}</span><strong>{s.code}</strong><small>{s.message}</small></div>)}</div></section>
<section className="card"><div className="cardhead"><h3>Recent real transactions</h3><span>Arbitrum Sepolia</span></div><div className="table"><div className="row head"><span>#</span><span>Decision</span><span>Result</span><span>Gas</span><span>Nonce</span><span>Explorer</span></div>{r.records.slice(-10).reverse().map(x=><div className="row" key={x.index}><span>{x.index}</span><span className={x.expected==="ALLOW"?"allow":"block"}>{x.expected}</span><span>{x.result}</span><span>{fmt(Number(x.gasUsed))}</span><span>{x.nonce}</span><a href={x.explorer} target="_blank" rel="noreferrer">{short(x.txHash)} ↗</a></div>)}</div></section>
<section className="card"><div className="cardhead"><h3>Deployed evidence</h3><span>Fresh benchmark deployment</span></div><div className="addresses">{Object.entries(r.deployments).map(([k,v])=><div key={k}><span>{k}</span><code>{v}</code></div>)}</div></section>
<footer>Evidence is generated from repository benchmark artifacts, not hardcoded dashboard values. Last run: {new Date(r.generatedAt).toLocaleString()}</footer></main>}
createRoot(document.getElementById("root")!).render(<App/>);
